import Link from 'next/dist/client/link'
import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import { useSession, signOut } from "next-auth/react"


export default function Home() {

  const { data: session } = useSession()
  const handleSignOut = () => {
    signOut()
  }

  return <>
    <Head>
      <title>Musicoon</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className='flex justify-center items-center py-2'>
      <h1 className="text-3xl font-bold  text-center">
        Musicoon
      </h1>
      {session ?
        <div>
          <p onClick={handleSignOut} className='text-xl text-right ml-5'>Sign out</p>
        </div> :
        <div>
          <Link href={"/login"}><p className='text-xl text-right ml-5'>Login</p></Link >
        </div>}

      <div className='ml-4'>
        {/* {session?.user.name} */}
      </div>


    </div>
    <main className='bg-black h-screen'>
      <Sidebar></Sidebar>
    </main>
  </>


}
