import { getSession } from 'next-auth/react'
import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Center from '../components/Center'
import { useSession } from "next-auth/react"


export default function Home() {

  const { data: session } = useSession()

  console.log(session);

  return (<>
    <Head>
      <title>Musicoon</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className='flex justify-center items-center py-2'>
      <h1 className="text-3xl font-bold  text-center">
        Musicoon
      </h1>

    </div>
    <main className='bg-black h-screen'>
      <div className='flex'>
        <Sidebar></Sidebar>
        <Center></Center>
      </div>
    </main>
  </>)
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session,
    }
  }
}
