import Head from 'next/head'
import Sidebar from '../components/Sidebar'
export default function Home() {
  return (
    <>
      <Head>
        <title>Sing With Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold  text-center">
        Sing With Me
      </h1>
      <main className='bg-black h-screen'>
        <Sidebar></Sidebar>
      </main>
    </>
  )
}
